version: '3.8'
services:
  mongodb:
    image: mongo:6
    restart: always
    environment:
      MONGO_INITDB_DATABASE: mydb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db
volumes:
  mongodata:
    driver: local